package org.serge.ws.rs.hk2.jersey;

import javax.inject.Qualifier;
import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Qualifier to bridge only expected services without system generated by HK2 container
 */
@Qualifier
@Documented
@Retention(RetentionPolicy.RUNTIME)
public @interface Spring {

    boolean lazy() default false;

}
