package org.serge.ws.rs.hk2.jersey;

import javax.inject.Qualifier;
import java.lang.annotation.Documented;

/**
 * Qualifier to bridge only expected services without system generated by HK2 container
 */
@Qualifier
@Documented
public @interface Spring {
}
